
services:

  backend:
    build:
      context: ${WORKDIR}/lms-backend-pipeline/LMS
      dockerfile: Dockerfile
    container_name: lms_backend
    restart: unless-stopped
    env_file:
      - ${WORKDIR}/lms-backend-pipeline/LMS/.env
    networks:
      - lms_net

  frontend:
    build:
      context: ${WORKDIR}/lms-frontend-pipeline/LMS_FrontEnd
      dockerfile: Dockerfile
    container_name: lms_frontend
    restart: unless-stopped
    networks:
      - lms_net

  nginx:
    build:
      context: /opt/LMS_Infra
      dockerfile: nginx/Dockerfile
    container_name: lms_nginx
    restart: unless-stopped
    ports:
    - "80:80"
    - "443:443"
    depends_on:
    - backend
    - frontend
    networks:
    - lms_net

networks:
  lms_net:
    driver: bridge

