
services:

  backend:
    build:
      context: ${WORKDIR}/${JOB_BASE_NAME}/LMS
      dockerfile: Dockerfile
    container_name: lms_backend
    restart: unless-stopped
    env_file:
      - ${WORKDIR}/${JOB_BASE_NAME}/LMS/.env
    networks:
      - lms_net

  frontend:
    build:
      context: ${WORKDIR}/${JOB_BASE_NAME}/LMS_FrontEnd
      dockerfile: Dockerfile
    container_name: lms_frontend
    restart: unless-stopped
    networks:
      - lms_net

  nginx:
    build:
      context: ${WORKDIR}/${JOB_BASE_NAME}/nginx
      dockerfile: Dockerfile
    container_name: lms_nginx
    restart: unless-stopped
    ports:
    - "80:80"
    - "443:443"
    volumes:
    - ${INFRA_DIR}/certs:/etc/nginx/certs:ro
    depends_on:
    - backend
    - frontend
    networks:
    - lms_net

networks:
  lms_net:
    driver: bridge

