
services:

  backend:
    build:
      context: ${WORKDIR}/LMS
      dockerfile: Dockerfile
    container_name: lms_backend
    restart: unless-stopped
    env_file:
      - ${WORKDIR}/LMS/.env
    networks:
      - lms_net

  frontend:
    build:
      context: ${WORKDIR}/LMS_FrontEnd
      dockerfile: Dockerfile
    container_name: lms_frontend
    args:
      VITE_API_BASE: ${VITE_API_BASE}
      VITE_SOCKET_URL: ${VITE_SOCKET_URL}
    restart: unless-stopped
    networks:
      - lms_net

  nginx:
    build:
      context: /opt/LMS_Infra/nginx
      dockerfile: Dockerfile
    container_name: lms_nginx
    restart: unless-stopped
    ports:
    - "80:80"
    - "443:443"
    volumes:
    - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
    - backend
    - frontend
    networks:
    - lms_net

networks:
  lms_net:
    driver: bridge

